# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            heechan
tagline:          'A Jekyll theme'
description:      ''
url:              https://heechan3006.github.io
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.
  
  
author:
  name:           'heechan'
  url:            https://heechan3006.github.io

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
                         
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true


# Disqus
disqus:
  enable: true
  shortname: https-heechan3006-github-io
  # hide comments (visitors need to click to load the comments)
  hide: false
  # count need to be false when hide is true
  count: true

google_fonts: "Lato&display=swap"
